// Generated by CoffeeScript 1.6.3
var instance;

instance = new prolific;

describe("Prolific", function() {
  it("should be a function", function() {
    return expect(typeof prolific).toBe("function");
  });
  describe("instance", function() {
    it("should be instantiated", function() {
      expect(instance).toBeDefined();
      expect(typeof instance).toBe("object");
      return console.log("instance", instance);
    });
    it("should have a test method", function() {
      expect(instance.test).toBeDefined();
      return expect(typeof instance.test).toBe("function");
    });
    return it("shoould not expose internal methods", function() {
      expect(instance.run_matcher).not.toBeDefined();
      return expect(instance.get_arguments).not.toBeDefined();
    });
  });
  describe("get attributes", function() {
    it("should have a method to get arguments from an assumption", function() {
      expect(instance.getArguments).toBeDefined();
      return expect(typeof instance.getArguments).toBe("function");
    });
    it("should catch a string", function() {
      var stringGetter;
      stringGetter = instance.getArguments("'this is my string'", "'asdasd'");
      return expect(stringGetter[0]).toBe("this is my string");
    });
    it("should catch a number", function() {
      var stringGetter;
      stringGetter = instance.getArguments("123", ".4");
      expect(stringGetter[0]).toBe(123);
      return expect(stringGetter[1]).toBe(.4);
    });
    it("should catch a math operation", function() {
      var stringGetter;
      stringGetter = instance.getArguments("(4/2*3+1)");
      return expect(stringGetter[0]).toBe(7);
    });
    it("should catch a variable", function() {
      var stringGetter;
      window.testVar = "test text";
      stringGetter = instance.getArguments("var testVar");
      return expect(stringGetter[0]).toBe("test text");
    });
    it("should catch an array", function() {
      var stringGetter;
      window.testVar = ["a", "b"];
      stringGetter = instance.getArguments("var testVar");
      return expect(stringGetter[0]).toEqual(["a", "b"]);
    });
    return it("should catch reserved types", function() {
      expect(void 0).toBe(instance.getArguments("undefined")[0]);
      expect(false).toBe(instance.getArguments("false")[0]);
      expect(true).toBe(instance.getArguments("true")[0]);
      return expect(null).toBe(instance.getArguments("null")[0]);
    });
  });
  describe("assumption matchers", function() {
    it("should have a method to match an assumption", function() {
      expect(instance.getMatcher).toBeDefined();
      return expect(typeof instance.getMatcher).toBe("function");
    });
    describe("matcher 'is greater|lower than'", function() {
      it("should catch 'a is greater than b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 is greater than 1");
        expect(matcher).toBe(instance.matchers["is greater|lower than"]);
        return expect(matcher.cond).toBe("greater");
      });
      it("should catch 'a is lower than b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 is lower than 4");
        expect(matcher).toBe(instance.matchers["is greater|lower than"]);
        return expect(matcher.cond).toBe("lower");
      });
      it("should catch 'a is > than b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 is > than 4");
        expect(matcher).toBe(instance.matchers["is greater|lower than"]);
        return expect(matcher.cond).toBe(">");
      });
      it("should catch 'a is < than b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 is < than 4");
        expect(matcher).toBe(instance.matchers["is greater|lower than"]);
        return expect(matcher.cond).toBe("<");
      });
      return it("should not catch 'a is bigger than b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 is bigger than 4");
        return expect(matcher).not.toBe(instance.matchers["is greater|lower than"]);
      });
    });
    describe("matcher 'is|isnt'", function() {
      it("should catch 'a is b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 is 2");
        expect(matcher).toBe(instance.matchers["is|isnt"]);
        return expect(matcher.cond).toBe("is");
      });
      it("should catch 'a isnt b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 isnt 2");
        expect(matcher).toBe(instance.matchers["is|isnt"]);
        return expect(matcher.cond).toBe("isnt");
      });
      return it("should not catch 'a equal to b' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 equal to 2");
        return expect(matcher).not.toBe(instance.matchers["is|isnt"]);
      });
    });
    describe("matcher 'is|isnt an element'", function() {
      it("should catch 'a is an element' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 is an element");
        expect(matcher).toBe(instance.matchers["is|isnt an element"]);
        return expect(matcher.cond).toBe("is");
      });
      return it("should catch 'a isnt an element' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("2 isnt an element");
        expect(matcher).toBe(instance.matchers["is|isnt an element"]);
        return expect(matcher.cond).toBe("isnt");
      });
    });
    return describe("matcher 'is <query>'", function() {
      return it("should catch '$(query) is .classname' assumption", function() {
        var matcher;
        matcher = instance.getMatcher("$('ciccio-pasticcio') is .ciccio-pasticcio");
        return expect(matcher.cond).toBe("is");
      });
    });
  });
  return describe("assume", function() {
    it("should expose a window.assume method", function() {
      return expect(window.assume).toBeDefined();
    });
    it("should be able to test 'is|isnt' assumptions", function() {
      assume("whenever is whenever");
      assume("3 is 3");
      assume("3 isnt '3'");
      assume("(4-1) is 3");
      assume("(3/2) is 1.5");
      assume("(4-2) isnt 3");
      assume("whenever isnt blabla");
      assume("true isnt 1");
      assume("true is true");
      assume("false isnt 0");
      assume("null isnt undefined");
      assume("var pippo is undefined");
      assume("var pippo isnt null");
      assume("var pippo isnt false");
      window.testme = "ciao";
      assume("var window.testme isnt undefined");
      assume("var window.testme isnt null");
      window.testnull = null;
      assume("var window.testnull isnt undefined");
      assume("var window.testnull is null");
      window.testfalse = false;
      assume("var window.testfalse isnt 0");
      assume("var window.testfalse is false");
      assume("var window.testfalse isnt true");
      assume("var window.testfalse isnt undefined");
      assume("var window.testfalse isnt null");
      $("body").append($('<div class="test" id="test"></div>'));
      assume("$('.test') is .test");
      assume("$('.test') is $('.test')");
      return assume("$('.test') is #test");
    });
    it("should be able to test 'is|isnt an element' assumptions", function() {
      assume("$('.ciccio-pasticcio') isnt an element");
      $("body").append($('<div class="ciccio-pasticcio"></div>'));
      return assume("$('.ciccio-pasticcio') is an element");
    });
    it("should be able to test 'is greater|lower|>|<' assumptions", function() {
      assume("4 is greater than 3");
      assume("4 is greater than 3.999999999");
      assume("4 is lower than (5*2-6+.000001)");
      assume("(4-3) is > than .5");
      window.a = 5;
      assume("var a is < than 6");
      return assume("var a is lower than (5+1)");
    });
    it("should be able to test more than one condition with and", function() {
      assume("5 is greater than 4 and 'pippo' isnt 'pluto'");
      return assume("var a is 5 and $('.ciccio-pasticcio') is an element");
    });
    return it("should wait given seconds before run the test", function() {
      window.a = 0;
      setTimeout(function() {
        return window.a = 1;
      }, 500);
      assume("in .51 seconds var a is 1");
      setTimeout(function() {
        return window.a = 2;
      }, 600);
      return assume("var a is 2 in 1 seconds");
    });
  });
});
